spring:
  application:
    name: yubi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.107.58:3306/BI
    username: root
#    password: 12345678
    password: chy0423
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    port: 6379
    host: 106.14.107.58
    password: chy0423
    database: 1
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://106.14.107.58:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 100MB
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
server:
  port: 8105
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        #学校机房上线需配置两项
#        same-site: none
#        secure: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
#      redis:
#        host: 106.14.107.58
#        port: 6379
#        password: chy0423
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 鱼聪明 AI 配置（https://yucongming.com/）
yuapi:
  client:
    access-key: u7v72j8bewucys85iuacwgiz4cp8ysm1
    secret-key: dyj9qlansecwbo88h33v0f7shppphrq4
